default: &default
  adapter: mysql2
  encoding: utf8mb4 
  pool: <%= ENV["DB_POOL"] || 5  %>
  timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_DB_USER'] %>
  password: <%= ENV['RDS_DB_PASS'] %>
  host: <%= ENV['RDS_DB_HOST'] %>

  # url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'dashboard' %>

test:
  <<: *default
  database: dashboard

production:
  <<: *default
  database: dashboard
  url: <%= ENV['DATABASE_URL'] %>
