default: &default
  adapter: postgresql
  encoding: unicode 
  pool: <%= ENV["DB_POOL"] || 5  %>
  timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>
  database: <%= ENV['DB_NAME'] || 'dashboard-dev' %>
  username: <%= ENV['DB_USER'] || 'dashboard-dev' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>

  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'dashboard-dev' %>

test:
  <<: *default
  database: dashboard-dev

production:
  <<: *default
  database: dashboard-dev
  url: <%= ENV['DATABASE_URL'] %>
